// Student controller
const Student = require('../models/Student');
const Order = require('../models/Order');

/**
 * Create student
 * body: { name: "Aarav" }
 * referralCode auto-generated by pre-save hook
 */
exports.createStudent = async (req, res, next) => {
  try {
    const { name } = req.body;
    if (!name || !name.trim()) {
      return res.status(400).json({ message: 'Name is required' });
    }
    const student = await Student.create({ name: name.trim() });
    return res.status(201).json({ student });
  } catch (err) {
    // handle duplicate referral code or other DB errors
    return next(err);
  }
};

/**
 * Get student details with optional orders populated
 * query param ?populateOrders=true to include order details
 */
exports.getStudent = async (req, res, next) => {
  try {
    const { id } = req.params;
    const populateOrders = req.query.populateOrders === 'true';

    let query = Student.findById(id).select('-__v');
    if (populateOrders) {
      query = query.populate({
        path: 'orders',
        select: 'snack quantity payableAmount createdAt',
        populate: { path: 'snack', select: 'title price' }
      });
    }

    const student = await query.lean();
    if (!student) return res.status(404).json({ message: 'Student not found' });

    return res.json({ student });
  } catch (err) {
    return next(err);
  }
};
